### ISSUE TITLE
DRC PL.2_3.3V mixes gate length rules with gate width rules

### ISSUE THREAD

**Issue by AL-255** [google/globalfoundries-pdk-libs-gf180mcu_fd_pr#107]
## Expected Behavior

W=0.22um, L=0.28um (the minimal PCell Size) shouldn't fail DRC

## Actual Behavior

![image](https://user-images.githubusercontent.com/2749714/219528308-86059ecc-7c23-40b5-a7dd-ff4305e04481.png)

## Steps to Reproduce the Problem

- Version: 11770e5e5bae2a2072899e7ef282c080e6c5d762
1. Instantiate a PCell with the default parameters
2. Run Klayout DRC

## Possible Cause

Rule PL.2_3.3V in gf180mcu.drc doesn't seem to check width and length separately (i.e. it assumes device width is always larger than length)

## References

[gf180mcu PDK Physical Verification](https://gf180mcu-pdk.readthedocs.io/en/latest/physical_verification/design_manual/drm_07_08.html#poly2)

@msaligane

**Comment by FaragElsayed2** [comment]
@atorkmabrains This issue has been addressed in [Efabless/PV repo](https://github.com/efabless/globalfoundries-pdk-libs-gf180mcu_fd_pv)

**Comment by atorkmabrains** [comment]
Thanks @FaragElsayed2
