### ISSUE TITLE
Shouldn't use `os.system` in Python scripts

### ISSUE THREAD

**Issue by mithro** [google/globalfoundries-pdk-libs-gf180mcu_fd_pr#21]
## Expected Behavior

You shouldn't use [`os.system`](https://docs.python.org/3/library/os.html#os.system) in Python scripts.

Examples;

Should use python internal functionality;

https://github.com/google/globalfoundries-pdk-libs-gf180mcu_fd_pr/blob/2e2eb4ad16e9f26ae80f7b0cad70dfd9a10da177/rules/klayout/lvs/testing/run_sc_regression.py#L105

https://github.com/google/globalfoundries-pdk-libs-gf180mcu_fd_pr/blob/2e2eb4ad16e9f26ae80f7b0cad70dfd9a10da177/rules/klayout/lvs/testing/run_sc_regression.py#L139

Should use `subprocess` module;

https://github.com/google/globalfoundries-pdk-libs-gf180mcu_fd_pr/blob/2e2eb4ad16e9f26ae80f7b0cad70dfd9a10da177/rules/klayout/lvs/testing/run_sc_regression.py#L138

## Actual Behavior

You should use inbuilt Python functions or the [`subprocess` module](https://docs.python.org/3/library/subprocess.html) like [`check_call`](https://docs.python.org/3/library/subprocess.html?highlight=check_call#subprocess.check_call) or [`check_output`](https://docs.python.org/3/library/subprocess.html?highlight=check_call#subprocess.check_output).

Instead of using `rm` you should use something like [`Path.unlink`](https://docs.python.org/3/library/pathlib.html?highlight=unlink#pathlib.Path.unlink) or [`os.unlink`](https://docs.python.org/3/library/os.html?highlight=unlink#os.unlink) or [`shutil.rmtree`](https://docs.python.org/3/library/shutil.html?highlight=shutil#shutil.rmtree).

**Comment by mithro** [comment]
https://github.com/google/globalfoundries-pdk-libs-gf180mcu_fd_pr/blob/2e2eb4ad16e9f26ae80f7b0cad70dfd9a10da177/rules/klayout/lvs/testing/run_sc_regression.py#L226

Should probably use https://docs.python.org/3/library/shutil.html?highlight=shutil#shutil.move or https://docs.python.org/3/library/os.html#os.rename or https://docs.python.org/3/library/os.html#os.replace

**Comment by atorkmabrains** [comment]
@mohanad0mohamed Could you please take care of this one soon?

**Comment by FaragElsayed2** [comment]
@atorkmabrains This issue has been addressed in [PV repo ](https://github.com/google/globalfoundries-pdk-libs-gf180mcu_fd_pv)

**Comment by atorkmabrains** [comment]
This has been addressed in PV repo as highlighted by @FaragElsayed2 

@mithro I'll close this issue. Please don't hesitate to open if you have any other concerns.
