### ISSUE TITLE
Scripts shouldn't use `time.sleep`

### ISSUE THREAD

**Issue by mithro** [google/globalfoundries-pdk-libs-gf180mcu_fd_pr#22]
## Expected Behavior

Scripts shouldn't use [`time.sleep`](https://docs.python.org/3/library/time.html?highlight=time%20sleep#time.sleep) to wait for things.

Examples @ 

https://github.com/google/globalfoundries-pdk-libs-gf180mcu_fd_pr/blob/2e2eb4ad16e9f26ae80f7b0cad70dfd9a10da177/rules/klayout/lvs/testing/run_sc_regression.py#L210

https://github.com/google/globalfoundries-pdk-libs-gf180mcu_fd_pr/blob/2e2eb4ad16e9f26ae80f7b0cad70dfd9a10da177/rules/klayout/lvs/testing/run_sc_regression.py#L223

## Actual Behavior

Instead the script should check for what is being waited on. Examples could be;
  - Checking if the output file exists.
  - Check if a process has completed.
  - Something else?

**Comment by atorkmabrains** [comment]
@mohanad0mohamed Could you please give this one a priority.
