### ISSUE TITLE
Apply python linting and formatting rules to this repository

### ISSUE THREAD

**Issue by mithro** [google/globalfoundries-pdk-libs-gf180mcu_fd_pr#53]
A lot of the Python scripts are not complying with standard python formatting rules. We should enable tools which check the files are complaint.

Some tools which we should look at are;
 - `pep8`
 - `black`
 - `pylint`
 - Something which checks for trailing whitespace.
 - Something which checks for license headers.

Setting these up can be showing by looking at the F4PGA repositories.

**Comment by mithro** [comment]
@umarcor - Can you help here?

**Comment by atorkmabrains** [comment]
@mohanad0mohamed Could you please take a look here?

**Comment by FaragElsayed2** [comment]
@atorkmabrains This issue has been addressed in [PV repo ](https://github.com/google/globalfoundries-pdk-libs-gf180mcu_fd_pv)

**Comment by atorkmabrains** [comment]
@FaragElsayed2 I think here is different. We still need linting for the code related to Pcells.

**Comment by FaragElsayed2** [comment]
@atorkmabrains I have assumed that we will add new Pcell generators. And for regression used in models, linting issues have been fixed in Mabrains/PR repo.

**Comment by atorkmabrains** [comment]
Thanks @FaragElsayed2 I could see the linting issues has been fixed in Mabrains and Efabless versions.

@mithro Could we close this issue?

**Comment by atorkmabrains** [comment]
@mithro I have opened another issue for merging of Efabless updates #109 . 

I'll close this issue. Please don't hesitate to open if you think we still need this issue. As soon as we update Google version with Efabless, we should have the linting code here.
