### ISSUE TITLE
Optimizing klayout DRC/LVS runs.

### ISSUE THREAD

**Issue by atorkmabrains** [google/globalfoundries-pdk-libs-gf180mcu_fd_pr#56]
We have seen that klayout DRC/LVS runs slow with Caravel layout. There is a need to optimize the DRC code to make it run faster and consume less memory.

**Comment by FaragElsayed2** [comment]
@atorkmabrains This issue has been addressed in [PV repo ](https://github.com/google/globalfoundries-pdk-libs-gf180mcu_fd_pv)

**Comment by atorkmabrains** [comment]
Thanks @FaragElsayed2 

All optimizations has been done for DRC/LVS in the PV repo.
