### ISSUE TITLE
5V devices extracted by Klayout LVS should be consistent with SPICE & xschem

### ISSUE THREAD

**Issue by egorxe** [google/globalfoundries-pdk-libs-gf180mcu_fd_pr#76]
Currently Klayout LVS script extracts pmos_5p0 and nmos_5p0 models for 5V transistors (see [here](https://github.com/google/globalfoundries-pdk-libs-gf180mcu_fd_pr/blob/74e4ec59b55bcf5be2f153abff8519d15ebe21fa/rules/klayout/lvs/gf180mcu.lvs#L1302) for example). This is inconsistent with SPICE deck which uses *mos_6p0 for both 5V and 6V transistors. Probably LVS script should be changed a bit to extract 6p0 models always.

If this change is OK (no 5p0 models planed in the future), I'll create a pull request.

**Comment by mithro** [comment]
@mkkassem & @atorkmabrains - Can you look into this?

**Comment by atorkmabrains** [comment]
@egorxe That's how the foundry made it. Not sure why GF decided to do that. But there is a different marker layer for the 5V devices. Please find the details of the Devices in the truth table:
https://gf180mcu-pdk.readthedocs.io/en/latest/physical_verification/design_manual/drm_04_4.html

Bascially, we followed the foundry recommendation in how it's done.

**Comment by egorxe** [comment]
@atorkmabrains Layers are different between 3.3V and 5/6V devices (Dualgate), but they are the same between 5V and 6V, only channel length is different. Anyway currently there is no *mos_5p0 models in SPICE deck, so it is impossible to perform LVS against known good SPICE netlist checked in simulation without netlist manipulations. So in my opinion either LVS scripts should be changed or *mos_5p0 should be aliased to *mos_6p0 in SPICE deck. There is no reason to close this issue until it's possible to pass LVS against simulated SPICE.

**Comment by mithro** [comment]
I think I agree with @egorxe that 
> the *mos_5p0 should be aliased to *mos_6p0 in SPICE deck

**Comment by atorkmabrains** [comment]
@mithro and @egorxe I need to review few things and get back to you.

**Comment by egorxe** [comment]
I would also like to note that even with any of changes suggested above, KLayout LVS still will not pass out of the box. KLayout extracts devices as SPICE models, but transistors in netlists from schematics are usually expressed as subcircuits. Subcircuits are translated into comprehensive models inside SPICE library (such as sm141064.ngspice) which can't be parsed by KLayout. 

To pass KLayout LVS one will have to manually replace all transistor instances in schematics netlist from subcircuits (X*) to models (M*). Or do the reverse replacement in netlist extracted with KLayout and perform comparison in netgen. This could be done with python script for example. It would be very useful to document some recommended  way to perform LVS with small example, cause currently it could be very hard to comprehend it for a newcomer.

**Comment by mithro** [comment]
@proppy - You where looking at LVS recently.

**Comment by atorkmabrains** [comment]
@egorxe There is an option I believe in xschem that generate an "lvs" net list rather than simulation net list as I remember. BTW, it's an industry standard to have different net lists for different purposes.

**Comment by egorxe** [comment]
> @egorxe There is an option I believe in xschem that generate an "lvs" net list rather than simulation net list as I remember. BTW, it's an industry standard to have different net lists for different purposes.

The only difference between "LVS" and "simulation" netlists in xschem is top level subcircuit declaration and some comments. And it's definitely not an industry standard to change netlists for different purposes by hand or to write custom scripts for each user. This is ineffective and error prone.  

The option in run_lvs.py for auto conversion of xschem netlists into KLayout LVS compatible format would be very helpful. I can provide an example of conversion routine if it will help.

BTW magic+netgen LVS flow from open_pdks extracts all transistors as *mos_6p0 subcircuits so it compares against xschem netlist without problems. Also SPICE deck compatible transistors allows magic LVS netlists to be simulated.

**Comment by atorkmabrains** [comment]
@egorxe I never said that you need to do it by hand or custom script in xschem. Unfortunately, I just realized that xschem doesn't do that out of the box. But it should. 

I have to disagree with you on industry standard. It is the industry to have different netlists based on usage from the schematic entry tool directly. Please refer to CDF manual in cadence virtuoso. There is always what is called an lvs view which is different than the hspice view, spectre view, eldospice view, etc...

You could try to find the actual virtuoso manual for CDF. 

References:

https://www.edaboard.com/threads/whats-cdf-of-cadence-whats-usage-tks.33063/

http://www-scf.usc.edu/~ee577/cadence_tutorial4.html

**Comment by egorxe** [comment]
@atorkmabrains I'm accustomed with Cadence and Mentor tools, thank you. And I'm not arguing with the idea of separate netlists. But xschem is not Virtuoso and KLayout (or Magic) is not Calibre. What I'm trying to say is that there should be documented and/or scripted way to pass LVS with current versions of open source EDA tools.

**Comment by atorkmabrains** [comment]
@egorxe There is, we already have done a video tutorial for that. But it's not published till now. 

Mabrains is trying to get the following tools to a state very close to the commercial custom design tools. (Side note: I worked for Mentor for almost 9 years on custom design tools and verification tools):
- Xschem
- Klayout

We don't focus on any other tools for now as Mabrains. We actually have even a library manager internally that is similar to the commercial tool and integrates everything and makes everything smooth.

Anyhow, ping me if you need more info.

**Comment by atorkmabrains** [comment]
@egorxe Take a look at our PLL design here:

https://github.com/mabrains/PLL_design

**Comment by atorkmabrains** [comment]
@egorxe As I told you, there is a way to create a netlist that is LVS compatible in xschem directly. Here is how according to Stephan reply:

The first option seems already implemented. The Xschem SImulation menu has the entry "use spiceprefix attribute". All devices that use this attribute (for example all sky130 mosfets) will be  netlisted as X-subcircuits if the spiceprefix (usually set to 'X') is used in the symbol and the option to use it is enabled in the SImulation menu. I need to understand if there is a different requirement for this specific issue.

Cc @mithro

**Comment by atorkmabrains** [comment]
https://github.com/StefanSchippers
Cc @stefanschippers

**Comment by egorxe** [comment]
> @egorxe I never said that you need to do it by hand or custom script in xschem. Unfortunately, I just realized that xschem doesn't do that out of the box. But it should.

Great!

> The first option seems already implemented. The Xschem SImulation menu has the entry "use spiceprefix attribute". All devices that use this attribute (for example all sky130 mosfets) will be netlisted as X-subcircuits if the spiceprefix (usually set to 'X') is used in the symbol and the option to use it is enabled in the SImulation menu.

Thanks, this seems to be it. I failed to actually test this way cause if I try to generate SPICE netlist in xschem without this "Simulation-Use spiceprefix attribute" option in menu, this check magically restores itself. But this is xschem, not LVS issue anyway. I hope this procedure will be documented in your video and text documentation.

> I need to understand if there is a different requirement for this specific issue.

@atorkmabrains Problem described in issue name still stands. There are no *mos_5p0 devices in SPICE deck or xschem (even here https://github.com/StefanSchippers/globalfoundries-pdk-libs-gf180mcu_fd_pr). Either LVS should extract everything as *mos6p0 or *mos5p0 should be added to SPICE deck and xschem. The only difference between 5V and 6V MOS KLayout PCells seems to be the presence of V5_XTOR marking layer (defined as marking here https://gf180mcu-pdk.readthedocs.io/en/latest/physical_verification/design_manual/drm_04_1.html). If this V5_XTOR layer does not influence masks is there a reason to separate 5V & 6V transistors in LVS? May be it's simpler to just represent 5V in LVS as *mos_6p0 as already done in SPICE and xschem?

**Comment by atorkmabrains** [comment]
@egorxe This is question to the foundry. We actually have sent that question to the foundry and didn't get a response yet. I'm not sure why they did that either. We fundamentally followed the foundry.

**Comment by egorxe** [comment]
@atorkmabrains Then I suggest to keep this issue open until *mos_5p0 devices are added into SPICE deck and xschem. They can be just aliases for *mos_6p0. I've changed this issue name a bit to reflect it.

**Comment by FaragElsayed2** [comment]
@atorkmabrains `mos_5p0 & mos_6p0` use same model but they are different in LVS as `mos_5p0` uses `dualgate & V5_xtor` marker layers but mos_6p0 uses `dualgate` layer only. So we need to use `mos_5p0` devices in LVS extraction as mentioned in DRM.

![image](https://user-images.githubusercontent.com/91015308/230779939-65a11da9-2100-47de-b3a4-f5ffe114860c.png)
https://gf180mcu-pdk.readthedocs.io/en/latest/physical_verification/design_manual/drm_04_1.html#drawn-layer-definition-and-abbreviation

![image](https://user-images.githubusercontent.com/91015308/230779988-2df1cc11-4da3-4c68-a955-5423b1c6ee77.png)
https://gf180mcu-pdk.readthedocs.io/en/latest/physical_verification/design_manual/drm_15.html#appendix-a-device-list-for-model-and-lvs-deck

![image](https://user-images.githubusercontent.com/91015308/230780013-38626d0c-21a2-4238-8402-804882d50d1e.png)
https://gf180mcu-pdk.readthedocs.io/en/latest/physical_verification/design_manual/drm_07_08.html#poly2

**Comment by atorkmabrains** [comment]
@mithro @mkkassem @RTimothyEdwards We need to reach out to GF for this.

**Comment by StefanSchippers** [comment]
`nfet_05v0.sym` can be added and can refer to the same spice model as `nfet_06v0.sym`.
The netlisting rule can be differentiated to accomodate LVS checking, while keeping the same netlist for spice sims.
xschem has 2 options (simulation menu) that are mostly used for LVS
- disable the spiceprefix (X) attribute so devices should be netlisted as `Mxxxx` instead of `XMxxxx`
- set LVS netlist. This will keep the top level wrapped inside a .subckt as usually happens with CDL netlists. When LVS netlist is set transistor symbols will use `lvs_format` attribute as the netlisting rule (if existing) instead of `format` to generate the netlist. This is already used to avoid generating the ad/as/pd/ps ... parameters that are not used in LVS.
We just need to know how Klayout extracts nfet_05v0 and nfet_06v0 to produce a matching netlist from xschem.

The above spiceprefix and LVS netlist flags can be set also from command line if we want to generate netlists from scripts, by setting tcl variables `spiceprefix` and `lvs_netlist`.

**Comment by atorkmabrains** [comment]
@StefanSchippers That would be a great update. Could you please do that and create PR on: https://github.com/efabless/globalfoundries-pdk-libs-gf180mcu_fd_pr for this?

**Comment by atorkmabrains** [comment]
I still think that we need to reach out to GF for this. 

@mithro @mkkassem @RTimothyEdwards
