### ISSUE TITLE
consider using a test framework

### ISSUE THREAD

**Issue by proppy** [google/globalfoundries-pdk-libs-gf180mcu_fd_pr#79]
## Expected Behavior

Tests should be using [python testing best practices](https://docs.python-guide.org/writing/tests/).

One popular framework is `pytest`: https://docs.pytest.org/en/7.2.x/ as it comes with:
- automated test discovery
- and a rich ecosystem of plugins: https://docs.pytest.org/en/7.2.x/reference/plugin_list.html#plugin-list (including things like https://pypi.org/project/pytest-xdist/ that allow multiple tests to be run concurrently).

## Actual Behavior

Tests uses monolytics python scripts with manual `exit()` invocation, see https://github.com/google/globalfoundries-pdk-libs-gf180mcu_fd_pr/blob/main/rules/klayout/drc/testing/run_regression.py#L243

**Comment by FaragElsayed2** [comment]
@atorkmabrains Did we hit this target in the new testing environment we have in PV repo ?

**Comment by atorkmabrains** [comment]
@FaragElsayed2 I don't believe so. I believe we still use the normal regression flow for PV. I recommend that we open another issue on PV repo and close this one.

**Comment by FaragElsayed2** [comment]
@atorkmabrains Should I do that or wait for @proppy to move it ?

**Comment by atorkmabrains** [comment]
@FaragElsayed2 Please open the other issue on the PV repo and we I'll close that one. Please make sure to link the new issue to this issue.

**Comment by FaragElsayed2** [comment]
@atorkmabrains Done

**Comment by atorkmabrains** [comment]
@FaragElsayed2 Could you please link it here?

**Comment by FaragElsayed2** [comment]
Refer to https://github.com/google/globalfoundries-pdk-libs-gf180mcu_fd_pv/issues/76

Cc @atorkmabrains

**Comment by atorkmabrains** [comment]
@proppy I'm closing this issue as we moved it to PV repo as @FaragElsayed2 has highlighted above.
